sudo: required
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- bolt execute-unit-tests
- bolt execute-feature-tests
- if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then make -C docs html; fi
deploy:
  provider: pypi
  user: IsaacRodriguez
  password:
    secure: fgbSPh0bdM6wSbEQIhgVjChZItegiFOloEmG3lU17JrzPVxPoJO0yjAp5j7DvRuEP+UTshTlksu/4Fv4Jmlsfxmr5AmtkuWjg1KoW10TI2AEi3xhn4cf4ZJof5P4QFdd4WCg+u9JcbWzwKN7cvXhkSaLe8SYw8skvsy4K29taRd+DhyLfdFETYXYIWcUOQ/oCYj6iZlSIj1EuAQjSKd7p6jLLUwIDsgGiNoVnn7i+BERGVOzEQsFVC4QsoEbXJB/jm0zv0cN3JZmPZkzqkxw4CdQ/xHS6EDoeOIYHe/DY97p3H545mtjNOc8TS0eYJhuhTeJhOAD0ngZO34N3ozOxmomu+ysT8rUIhFd0Uy0eDaYDEsk+nQHA4aNazSVNDN6i9mkjb8WHVmtlAj5pLKbEjYMX9HUBTjrrngNrMcB101tzmpFmb09oPxe2aFURMbt9GKd4p55iAwGu+M7BNwcw2rDHhTzHUNc3y9bRrIDa+DwbM6jEjCOm6ELGujfcA1zin+0sgfA+l4TDEuYlofKWlfPZiTEqveLNkhquCR+cMLKKHY7UNcqQwnbWzdIDCKFTK/mH72zwxQ0EyNy5O8eVsJvJdFwgXg3DdNKTKpfmwAwhIVOcNl138Dvbqkddamv7HchXyAeNvXgCSRHjV0o+XyUNby1OUepMSLZFyfoTN4=
  on:
    tags: true
    distributions: "bdist_wheel"
    repo: behave-restful/behave-restful
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = 3.6
notifications:
  slack:
    secure: um1fqygbv7EDw8BjN5yk8Al5XdTXFY971dSTO6w3LMGVYWFDna/4fH7UUU/SZZQ/tQyfQ1xy+xIhFBoqIpcNV2FNpF4J6hNOULwBHMesEWUNaoaSWx2dRxrsEdKmLQ7iO4PnpAs6QcXOpYuXUqJSPB6Lg0G85KFRk79fROtrD5IrhmduLtyDEp2WOSKqL8DuFqEa+cg+IIEUGRAWjP6Aqhcb/RuEstmaIeI9eBtGK0gcxagcFGZuDfE9HVAANpQKGINpTxlM46rGb0pFs3UpbtxoyElqH8jRZGxw++PRbbkyI37on25nlJvdYujza6gnYWs9XiaMTeV/6Rq7RQgXPbO9ykmNG4naracG+oHRtbS7q3Crlc2u1KsUAiSUouh+Rh0KPmT58S7O4V7f7ZmIi9R+4kzAHURtvtTpO4fXwCLZ4ww5CDUKW9JiK0O9TPjT0ep3Ssrnp0jwx3s9R0wtzbE6CoyB3Tl/OrkI91L3o4qgjXRWBYNnFhlSlesDonEpX2/EIOEG0TVDRWWC+hePOxT8mGwFb/mYjvOy14JmcrDnFCoUo2Acp6g+DUEwf8WKpiq80i4Om5EjeoqQIBizcvmaGv0HqlhffE8A3gmTQv1rk3/CutIHE7qK/CJrbUYeqEMjdSsa7cr51zA8pSDXEYKFFI8eK8Fc7bwQQozv9YE=
    email: false
    